spring:
  datasource:
    url: jdbc:mysql://localhost:3306/big_event
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 666666
  data:
    redis:
      host: localhost
      port: 6379
      password: redis6379


# jwt令牌秘钥和过期时间
jwt-utils:
  key: iob&(@$&123nsan24++kf2./japdf
  expiration-time: 24*60*60*1000


mybatis:
  configuration:
    map-underscore-to-camel-case: true  # 开启下划线和驼峰命名的转化
